repos:
  - repo: https://github.com/PyCQA/flake8
    rev: 3.9.2
    hooks:
      - id: flake8
        args: [--max-line-length=95]
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        language_version: python3.10
  - repo: local
    hooks:
      - id: verify-py-deps
        name: verify-py-deps
        entry: ./scripts/verify-py-deps.sh
        language: system
        files: (.*/)?Pipfile(.lock)?
        pass_filenames: true
